max_connections = 200
shared_buffers = 256MB                  
checkpoint_completion_target = 0.9      
synchronous_commit = off                
work_mem = 16MB                         

wal_level = replica
archive_mode = on
archive_command = 'cp %p /wal_archive/%f'
archive_timeout = 60

listen_addresses = '*'
